name: Metrics

on:
  schedule: [ { cron: "0 0 * * *" } ]
  workflow_dispatch:
  push: { branches: [ "master", "main" ] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_MU88_LOWLIGHTER_ID }}
          private-key: ${{ secrets.APP_MU88_LOWLIGHTER_PRIVATE_KEY }}

      - name: Create metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ steps.app-token.outputs.token }}
          # token: ${{ secrets.LOWLIGHTER_TOKEN }}
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 4919526
          plugin_stackoverflow_sections: answers-top, questions-top
