name: Metrics
on:
  # Schedule daily updates
  schedule: [ { cron: "0 0 * * *" } ]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: [ "master", "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.LOWLIGHTER_TOKEN }}
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 4919526
          plugin_stackoverflow_sections: answers-top, questions-top